import {initializeApp} from 'firebase/app';
import {getAuth, signInWithPopup, GoogleAuthProvider, OAuthProvider, signInWithEmailAndPassword, getMultiFactorResolver, TotpMultiFactorGenerator, multiFactor, setPersistence, inMemoryPersistence, signOut} from 'firebase/auth';
let auth=null;
async function initialize(){const r=await fetch('/api/v1/auth/public-config',{signal:AbortSignal.timeout(15000)});const c=await r.json();if(!c.enabled)return false;auth=getAuth(initializeApp({apiKey:c.apiKey,authDomain:c.authDomain,projectId:c.projectId}));await setPersistence(auth,inMemoryPersistence);return true;}
async function challenge(error){if(error.code!=='auth/multi-factor-auth-required')throw error;const resolver=getMultiFactorResolver(auth,error);const hint=resolver.hints.find(h=>h.factorId===TotpMultiFactorGenerator.FACTOR_ID);if(!hint)throw new Error('Secondo fattore non supportato: contatta il responsabile.');const code=prompt('Codice a 6 cifre dell’app di autenticazione:');if(!code)throw new Error('Accesso annullato.');return resolver.resolveSignIn(TotpMultiFactorGenerator.assertionForSignIn(hint.uid,code.trim()));}
async function login(provider,email,password){if(!auth&&!await initialize())throw new Error('Accesso federato non configurato dal responsabile.');let credential;try{credential=provider?await signInWithPopup(auth,provider==='google'?new GoogleAuthProvider():new OAuthProvider('microsoft.com')):await signInWithEmailAndPassword(auth,email,password);}catch(e){credential=await challenge(e);}const token=await credential.user.getIdToken();const refreshToken=credential.user.refreshToken;const response=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken:token}),signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok){await signOut(auth);throw new Error(data.message||'Account aziendale non autorizzato.');}return{...data,token,refreshToken};}
async function enrollTotp(){if(!auth?.currentUser)throw new Error('Accedi con email o SSO prima di configurare MFA.');const session=await multiFactor(auth.currentUser).getSession();const secret=await TotpMultiFactorGenerator.generateSecret(session);const uri=secret.generateQrCodeUrl(auth.currentUser.email||'RadioTech','RadioTech');const code=prompt(`Aggiungi questa chiave alla tua app di autenticazione:\n${secret.secretKey}\n\nURI: ${uri}\n\nPoi inserisci il codice a 6 cifre:`);if(!code)return;await multiFactor(auth.currentUser).enroll(TotpMultiFactorGenerator.assertionForEnrollment(secret,code.trim()),'RadioTech TOTP');return true;}
window.RadioTechFederation={initialize,login,enrollTotp,logout:async()=>{if(auth)await signOut(auth);}};
document.addEventListener('DOMContentLoaded',async()=>{try{if(!await initialize())return;const form=document.getElementById('loginForm');if(!form)return;for(const [provider,label]of[['google','Accedi con Google'],['microsoft','Accedi con Microsoft']]){const button=document.createElement('button');button.type='button';button.className='btn';button.textContent=label;button.onclick=async()=>{button.disabled=true;try{const result=await login(provider);window.dispatchEvent(new CustomEvent('radiotech:sso',{detail:result}));}catch(e){document.getElementById('loginStatus').textContent=e.message;}finally{button.disabled=false;}};form.append(button);}}catch{/* Federation disabled or config unavailable; password/QR stay usable. */}});
