package com.radiotech.radiotech_backend.ops;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.firebase.*;
import com.google.firebase.auth.*;
import com.google.firebase.cloud.FirestoreClient;
import com.google.cloud.firestore.*;
import com.google.cloud.Timestamp;
import com.google.cloud.storage.*;
import tools.jackson.databind.json.JsonMapper;
import java.nio.file.*;
import java.util.*;
import javax.crypto.*;
import javax.crypto.spec.*;

/** Trusted operator CLI: encrypted export, verification and emulator-only restore. */
public final class BackupTool {
 private static final JsonMapper JSON=JsonMapper.builder().build();
 public static byte[] encrypt(byte[] plain,byte[] key)throws Exception{if(key.length!=32)throw new IllegalArgumentException("32-byte key required");byte[] nonce=new byte[12];new java.security.SecureRandom().nextBytes(nonce);var cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,nonce));return java.nio.ByteBuffer.allocate(12+plain.length+16).put(nonce).put(cipher.doFinal(plain)).array();}
 public static byte[] decrypt(byte[] data,byte[] key)throws Exception{if(data.length<28||key.length!=32)throw new IllegalArgumentException("Invalid backup/key");var cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,new SecretKeySpec(key,"AES"),new GCMParameterSpec(128,Arrays.copyOfRange(data,0,12)));return cipher.doFinal(Arrays.copyOfRange(data,12,data.length));}
 public static Object encode(Object value){
  if(value==null)return Map.of("t","null");if(value instanceof Map<?,?> m){var encoded=new LinkedHashMap<String,Object>();m.forEach((k,v)->encoded.put(k.toString(),encode(v)));return Map.of("t","map","v",encoded);}if(value instanceof List<?> list)return Map.of("t","list","v",list.stream().map(BackupTool::encode).toList());
  if(value instanceof Timestamp t)return Map.of("t","timestamp","seconds",String.valueOf(t.getSeconds()),"nanos",t.getNanos());if(value instanceof GeoPoint p)return Map.of("t","geo","lat",p.getLatitude(),"lon",p.getLongitude());if(value instanceof DocumentReference r)return Map.of("t","reference","v",r.getPath());if(value instanceof com.google.cloud.firestore.Blob b)return Map.of("t","blob","v",Base64.getEncoder().encodeToString(b.toBytes()));
  if(value instanceof Number n)return Map.of("t",n instanceof Double||n instanceof Float?"double":"integer","v",n.toString());if(value instanceof Boolean)return Map.of("t","bool","v",value);if(value instanceof String)return Map.of("t","string","v",value);throw new IllegalArgumentException("Unsupported Firestore value: "+value.getClass());
 }
 public static Object decode(Object input,Firestore db){var m=(Map<String,Object>)input;return switch(m.get("t").toString()){
  case "null"->null;case "map"->{var result=new LinkedHashMap<String,Object>();((Map<String,Object>)m.get("v")).forEach((k,v)->result.put(k,decode(v,db)));yield result;}case "list"->((List<?>)m.get("v")).stream().map(v->decode(v,db)).toList();case "integer"->Long.parseLong(m.get("v").toString());case "double"->Double.parseDouble(m.get("v").toString());case "bool","string"->m.get("v");case "timestamp"->Timestamp.ofTimeSecondsAndNanos(Long.parseLong(m.get("seconds").toString()),((Number)m.get("nanos")).intValue());case "geo"->new GeoPoint(((Number)m.get("lat")).doubleValue(),((Number)m.get("lon")).doubleValue());case "reference"->db.document(m.get("v").toString());case "blob"->com.google.cloud.firestore.Blob.fromBytes(Base64.getDecoder().decode(m.get("v").toString()));default->throw new IllegalArgumentException("Unknown backup value type");};}
 private static void collection(CollectionReference collection,List<Map<String,Object>> output)throws Exception{for(var ref:collection.listDocuments()){var doc=ref.get().get();if(doc.exists())output.add(Map.of("path",ref.getPath(),"data",encode(doc.getData())));for(var child:ref.listCollections())collection(child,output);}}
 public static Map<String,Object> snapshot(Firestore db)throws Exception{var documents=new ArrayList<Map<String,Object>>();for(var c:db.listCollections())collection(c,documents);return new LinkedHashMap<>(Map.of("schema",1,"createdAt",java.time.Instant.now().toString(),"documents",documents));}
 public static List<Map<String,Object>> snapshotLocalFiles(Path root)throws Exception{var files=new ArrayList<Map<String,Object>>();if(!Files.isDirectory(root))return files;try(var paths=Files.list(root)){for(Path file:paths.filter(Files::isRegularFile).toList()){String name=file.getFileName().toString();if(!name.matches("[a-f0-9]{64}\\.(bin|json)"))continue;if(Files.size(file)>20_000_000)throw new IllegalArgumentException("Local file too large for test backup");files.add(Map.of("name",name,"data",Base64.getEncoder().encodeToString(Files.readAllBytes(file))));}}return files;}
 public static void restoreLocalFiles(List<Map<String,Object>> files,Path destination)throws Exception{Files.createDirectories(destination);for(var file:files){String name=file.get("name").toString();if(!name.matches("[a-f0-9]{64}\\.(bin|json)"))throw new IllegalArgumentException("Invalid local backup path");Files.write(destination.resolve(name),Base64.getDecoder().decode(file.get("data").toString()),StandardOpenOption.CREATE_NEW);}}
 public static void restoreDocuments(Map<String,Object> backup,Firestore db)throws Exception{if(System.getenv("FIRESTORE_EMULATOR_HOST")==null||!db.getOptions().getProjectId().startsWith("demo-"))throw new SecurityException("Restore is allowed only to a demo Firestore emulator.");for(var record:(List<Map<String,Object>>)backup.get("documents")){String path=record.get("path").toString();if(path.startsWith("/")||path.contains("..")||path.split("/").length%2!=0)throw new IllegalArgumentException("Invalid document path");db.document(path).set((Map<String,Object>)decode(record.get("data"),db)).get();}}
 public static void main(String[] args)throws Exception{
  if(args.length!=3||!Set.of("export","verify","restore-emulator").contains(args[0]))throw new IllegalArgumentException("Usage: export|verify|restore-emulator archive key-file");Path archive=Path.of(args[1]),keyPath=Path.of(args[2]);byte[] key=Files.readAllBytes(keyPath);
  if(args[0].equals("verify")){var backup=JSON.readValue(decrypt(Files.readAllBytes(archive),key),Map.class);System.out.println("Authenticated archive OK; documents="+((List<?>)backup.get("documents")).size()+", users="+((List<?>)backup.get("users")).size()+", files="+((List<?>)backup.get("files")).size()+", localFiles="+((List<?>)backup.getOrDefault("localFiles",List.of())).size());return;}
  String project=System.getenv("FIREBASE_PROJECT_ID");if(project==null||project.isBlank())throw new IllegalArgumentException("FIREBASE_PROJECT_ID required");String account=System.getenv("FIREBASE_SERVICE_ACCOUNT_PATH"),bucket=System.getenv("FIREBASE_STORAGE_BUCKET");GoogleCredentials credentials=account==null?GoogleCredentials.getApplicationDefault():GoogleCredentials.fromStream(Files.newInputStream(Path.of(account)));var options=FirebaseOptions.builder().setProjectId(project).setCredentials(credentials);if(bucket!=null&&!bucket.isBlank())options.setStorageBucket(bucket);FirebaseApp.initializeApp(options.build());var db=FirestoreClient.getFirestore();
  try{
   if(args[0].equals("restore-emulator")){if(System.getenv("FIREBASE_AUTH_EMULATOR_HOST")==null||!project.startsWith("demo-"))throw new SecurityException("Demo Auth emulator required.");var backup=JSON.readValue(decrypt(Files.readAllBytes(archive),key),Map.class);restoreDocuments(backup,db);restoreLocalFiles((List<Map<String,Object>>)backup.getOrDefault("localFiles",List.of()),Path.of(".dist/restored-private-files-"+java.time.Instant.now().toEpochMilli()));for(var data:(List<Map<String,Object>>)backup.get("users")){String uid=data.get("uid").toString();try{FirebaseAuth.getInstance().getUser(uid);}catch(FirebaseAuthException e){var request=new UserRecord.CreateRequest().setUid(uid).setDisabled(true);if(data.get("email")!=null)request.setEmail(data.get("email").toString());FirebaseAuth.getInstance().createUser(request);}FirebaseAuth.getInstance().setCustomUserClaims(uid,(Map<String,Object>)data.get("claims"));}System.out.println("Emulator restore completed; imported accounts disabled, reset passwords before reconnecting.");return;}
   var backup=snapshot(db);backup.put("projectId",project);var users=new ArrayList<Map<String,Object>>();for(var user:FirebaseAuth.getInstance().listUsers(null).iterateAll()){var r=new LinkedHashMap<String,Object>();r.put("uid",user.getUid());r.put("email",user.getEmail());r.put("displayName",user.getDisplayName());r.put("disabled",user.isDisabled());r.put("emailVerified",user.isEmailVerified());r.put("claims",user.getCustomClaims());r.put("passwordHash",user.getPasswordHash());r.put("passwordSalt",user.getPasswordSalt());r.put("providers",Arrays.stream(user.getProviderData()).map(p->Map.of("providerId",p.getProviderId(),"uid",p.getUid())).toList());users.add(r);}backup.put("users",users);
   var files=new ArrayList<Map<String,Object>>();if(bucket!=null&&!bucket.isBlank()){var storage=StorageOptions.newBuilder().setProjectId(project).setCredentials(credentials).build().getService();for(var file:storage.list(bucket).iterateAll()){if(file.getSize()>20_000_000)throw new IllegalArgumentException("Large object requires managed streaming backup: "+file.getName());var r=new LinkedHashMap<String,Object>();r.put("name",file.getName());r.put("contentType",file.getContentType());r.put("metadata",file.getMetadata());r.put("data",Base64.getEncoder().encodeToString(file.getContent()));files.add(r);}}backup.put("files",files);backup.put("localFiles",snapshotLocalFiles(Path.of(System.getenv().getOrDefault("RADIOTECH_LOCAL_FILES_DIRECTORY",".dist/private-files"))));backup.put("storageStatus",bucket==null||bucket.isBlank()?"NOT_CONFIGURED":"EXPORTED");backup.put("authPasswordRestore","Production import requires Firebase password-hash configuration, MFA/provider recovery and independent restore review.");
   Files.createDirectories(archive.toAbsolutePath().getParent());Path temp=archive.resolveSibling(archive.getFileName()+".partial");Files.write(temp,encrypt(JSON.writeValueAsBytes(backup),key));Files.move(temp,archive,StandardCopyOption.ATOMIC_MOVE);System.out.println("Encrypted backup completed; documents="+((List<?>)backup.get("documents")).size()+", users="+users.size()+", files="+files.size()+", storage="+backup.get("storageStatus"));
  }finally{db.close();FirebaseApp.getInstance().delete();}
 }
}
